name: Bug Report
description: Create a report to help us improve Notion-VSCode
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
      placeholder: 'The Notion tree view fails to load after updating to the latest version.'
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: 'To Reproduce'
      description: 'Steps to reproduce the behavior:'
      placeholder: |
        1. In VS Code, open the Notion extension
        2. Click the refresh button
        3. See error message
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'Expected behavior'
      description: 'A clear and concise description of what you expected to happen.'
      placeholder: 'The tree view should display all pages and databases from my Notion workspace.'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain your problem.'
  - type: textarea
    id: environment
    attributes:
      label: 'Environment'
      placeholder: |
        - VS Code version: [e.g. 1.95.0]
        - Extension version: [e.g. 1.0.3]
        - OS: [e.g. macOS, Windows, Linux]
        - Notion workspace type: [e.g. personal, workspace]
  - type: textarea
    id: logs
    attributes:
      label: 'Error logs or stack trace'
      description: 'If available, paste any error messages or logs from the VS Code console.'
      placeholder: 'Open Developer Tools (Help > Toggle Developer Tools) and copy any error messages.'
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the problem here.'
      placeholder: 'This bug happens when using a Notion token with limited permissions. It works fine with a full-access token.'
